version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - '{{ checksum "go.sum" }}'
      - run: echo "$DOCKER_HUB_PASS" | docker login --username $DOCKER_HUB_USER --password-stdin
      - run: make docker-build
      - run: make docker-push
      - save_cache:
          key: '{{ checksum "go.sum" }}'
          paths:
            - /tmp/go/cache
            - /go/pkg/mod

  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ checksum "go.sum" }}'
      - run: make test
      - run: make bench
      - save_cache:
          key: '{{ checksum "go.sum" }}'
          paths:
            - /tmp/go/cache
            - /go/pkg/mod

workflows:
  version: 2

  master:
    jobs:
      - test
      - lint
      - build:
          requires:
            - test
            - lint
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
