version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - '{{ checksum "go.sum" }}'
      - run: echo "$DOCKER_HUB_PASS" | docker login --username $DOCKER_HUB_USER --password-stdin
      - run: make docker
      - store_artifacts:
          path: dist
      - run: make docker-push
      - save_cache:
          key: '{{ checksum "go.sum" }}'
          paths:
            - /tmp/go/cache
            - /go/pkg/mod

  upload:
    docker:
    - image: circleci/golang
    steps:
      - checkout
      - run: go get -u github.com/tcnksm/ghrs
      - run: ghr v${CIRCLE_TAG} release/${CIRCLE_TAG} -r mona -u ${CIRCLE_USERNAME}

  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ checksum "go.sum" }}'
      - run: make test
      - save_cache:
          key: '{{ checksum "go.sum" }}'
          paths:
            - /tmp/go/cache
            - /go/pkg/mod

workflows:
  version: 2
  feature:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /feature\/.*/
      - lint:
          filters:
            branches:
              only:
                - /feature\/.*/

  master:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master

      - upload:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - build
