version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - '{{ checksum "go.sum" }}'
      - run: echo "$DOCKER_HUB_PASS" | docker login --username $DOCKER_HUB_USER --password-stdin
      - run: make docker
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: release
      - run: make docker-push
      - save_cache:
          key: '{{ checksum "go.sum" }}'
          paths:
            - /tmp/go/cache
            - /go/pkg/mod
      - save_cache:
          key: '{{ .Environment.CIRCLE_SHA1 }}'
          paths:
            - release

  upload:
    docker:
    - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
          keys: 
            - '{{ .Environment.CIRCLE_SHA1 }}'
      - run: go get github.com/aktau/github-release
      # Create GitHub release
      - run: github-release release --tag ${CIRCLE_TAG} --repo mona --user ${CIRCLE_USERNAME}
      # Upload files
      - run: github-release upload --tag ${CIRCLE_TAG} --repo mona --user ${CIRCLE_USERNAME} --file release/*

  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang
    environment:
      CGO_ENABLED: "0"
      GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ checksum "go.sum" }}'
      - run: make test
      - save_cache:
          key: '{{ checksum "go.sum" }}'
          paths:
            - /tmp/go/cache
            - /go/pkg/mod

workflows:
  version: 2
  feature:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /feature\/.*/
      - lint:
          filters:
            branches:
              only:
                - /feature\/.*/

  master:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master

      - upload:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - build
