version: 2.1

jobs:
  build:
    docker:
      - image: golang:alpine
    steps:
      - checkout
      - run: make build
      - store_artifacts:
        path:
        - dist

  lint:
    docker:
      - image: golangci-lint:v1.16.0 
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: golang:alpine
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  feature:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /feature\/.*/
      - lint:
          filters:
            branches:
              only:
                - /feature\/.*/

  master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master